### ISSUE TITLE
oauth2client 2.0 migration 

### ISSUE THREAD

**Issue by sandeepkoduri** [cloudendpoints/endpoints-management-python#21]
I was waiting for using custom domains for 2 years now, after the release of Google CloudEndpoints 2.0, I am still struck because I am using google-api-python-client latest version for quite some time now, which is dependent on using oauth2client 2.0. 

I posted regarding this few months ago.
https://github.com/cloudendpoints/endpoints-python/issues/16

this is situation with oauth2client 2.0 and endpoints 2.0
`  File "default/src/libs/google/api/gen/servicecontrol_v1_messages.py", line 25, in <module>
    from apitools.base.py import encoding
  File "default/src/libs/apitools/base/py/__init__.py", line 22, in <module>
    from apitools.base.py.credentials_lib import *
  File "default/src/libs/apitools/base/py/credentials_lib.py", line 28, in <module>
    import oauth2client.gce
ImportError: No module named gce`

Looking if this would be updates. We are not happy to run the product domain in appspot.com for more than a year, for choosing clound endpoints.

**Comment by kautilya-pro** [comment]
Our team is also facing similar issues.
We wonder why this module is still using very old other google libraries.

Looking forward for a resolved update sooner. Thank you.

**Comment by fili** [comment]
It actually also impacts endpoints and apitools for another reason:

```
/apitools/base/py/credentials_lib.py", line 71, in <module>
    from oauth2client import multistore_file
ImportError: cannot import name multistore_file
```

Could only find this solution (which is to downgrade): https://stackoverflow.com/a/44266031

**Comment by inklesspen** [comment]
Unfortunately oauth2client 4.0.0 and higher cannot run on App Engine, because it uses ctypes. (That is, the `multiprocess_file_storage` module, which is the replacement for `multistore_file`, ends up using ctypes, because it uses fasteners, which uses monotonic, which uses ctypes.)

oauth2client 3.0.0 is known to work and is currently our pinned version. This version should work properly with the latest apitools.

**Comment by fili** [comment]
I was able to use the latest version of oauth2client on GAE without endpoints. So it seems to me that this is a dependency issue for endpoints, not oauth2client, on app engine. I actually had to downgrade to use both (as you suggested).

**Comment by inklesspen** [comment]
oauth2client itself probably works fine on Endpoints. The problem is the `oauth2client.contrib.multiprocess_file_storage` module, which is used by `apitools.base.py.credentials_lib`, which is used by the management framework. If your code on GAE did not use `multiprocess_file_storage`, it would not have triggered the problem.
